### ISSUE TITLE
Norlin Claims Returned Report

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#123]

**Comment by AmeliaDS** [comment]
--Returns a list of all items marked 'Claimed returned' across selected Norlin Library locations.
SELECT DISTINCT
	lt.item_status AS status,
	lt.claimed_returned_date AS claim_date,
	it.barcode AS barcode,
	lt2.name AS location,
	hrt.call_number AS call_number,
	it.copy_number AS copy_number,
	it.volume AS volume,
	it2.title AS title,
	lt.action_comment AS note,
	lt.user_id AS patron_uuid
FROM folio_circulation.loan__t__ lt 
LEFT JOIN folio_inventory.item__t__ it ON it.id = lt.item_id
LEFT JOIN folio_inventory.location__t__ lt2 ON lt2.id = lt.item_effective_location_id_at_check_out  --or lt2.id = it.effective_location_id 
LEFT JOIN folio_inventory.holdings_record__t__ hrt ON hrt.id = it.holdings_record_id
LEFT JOIN folio_inventory.instance__t__ it2 ON it2.id = hrt.instance_id
WHERE lt.item_status = 'Claimed returned'
	AND lt2.code IN ('ART','ARTST','ARTOV','ARTREF','ASN','ASNST','ASNOV','ASNCIRREF', 'CYA','CYAST'
	,'NORGEN','NORRES','NORGSC','NORDC','NORED','NORRAD','NORDIS','NORDVD','NOROV','NORST','PASCAL','PEROV','PERST'
	,'NORPOP','REFCIR','SCIST','SCIOV','SCIREF')
	AND call_number IS NOT NULL
ORDER BY claim_date
;
 
/*Results & Questions:
-Runs and returns 27 results, just a few over what I estimated there should be (9/15/23).
-Is SELECT DISTINCT an acceptable way to eliminate duplicate rows, or should I do something differently?
-Should I simplify the location range to a library location rather than item locations, 
since non-circulating items should not end up with claims? This would also cover other 
Nor depts like Gov and Rad who previously managed their own claims, but may not have dedicated queries.
-Where can I connect to patron tables to get patron barcodes, or should we stick with uuid as it is unique, 
random gen, and guaranteed to exist for every patron record?
*/
