### ISSUE TITLE
Course Reserves Title List

### ISSUE THREAD

**Issue by steveellis** [culibraries/library-reporting#33]
Per @katallm - important but not urgent

Wiki Page: https://github.com/culibraries/library-reporting/wiki/Issue-33:-Open-Reserves-Titles-List

**Comment by arthur-aguilera** [comment]
Wiki Page: https://github.com/culibraries/library-reporting/wiki/Issue-33:-Open-Reserves-Titles-List

**Comment by steveellis** [comment]
@katallm Can you confirm that this is ok to run as an in-app report. If so maybe close out this issue.

**Comment by katallm** [comment]
Courses in-app reporting is adequate for go-live. 

Just making a note that as we move into the second semester and beyond with FOLIO, we'll need to develop a query. It's not essential to day-to-day, but it will become a high priority "nice to have", so that we can export and save previous semesters' data. This may change as we develop new practices, but as is, staff usually clean up course reserve records on a regular basis, and the ability to easily export data on previous courses and items on reserve is extremely helpful in completing that work.
